// typography.ts
export type TypographyColor =
  | 'blue40'
  | 'blue50'
  | 'blue60'
  | 'sliver'
  | 'gray'
  | 'graphite'
  | 'hightBlue'
  | 'mediumDark'
  | 'mediumWhite'
  | 'inherit'
  | 'white'
  | 'black'
  | 'greyBlue'
  | 'lightGrey'
  | 'mediumGrey'
  | 'darkGrey'
  | 'dark';
